---
version: '3.7'

services:
  mysql:
    image: mysql:5.7
    volumes:
      - mysqldata:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "secret"
      MYSQL_DATABASE: "db_qa_session"
    restart: unless-stopped
    ports:
      - 3306:3306

volumes:
  mysqldata:
